# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: densenet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='densenet.proto',
  package='object_detection.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x64\x65nsenet.proto\x12\x17object_detection.protos\"\x91\x04\n\x08\x44\x65nseNet\x12\x0e\n\x06k_size\x18\x01 \x01(\x05\x12\t\n\x01L\x18\x02 \x01(\x05\x12\x10\n\x08\x62ias_add\x18\x03 \x01(\x08\x12\x14\n\x0c\x64\x65nse_blocks\x18\x04 \x01(\x05\x12\x12\n\nblock_size\x18\x05 \x03(\x05\x12\x12\n\ndensenet_b\x18\x06 \x01(\x08\x12\x0f\n\x07\x64ropout\x18\x07 \x01(\x08\x12\x14\n\x0c\x64ropout_rate\x18\x08 \x01(\x02\x12\x12\n\ndensenet_c\x18\t \x01(\x08\x12\r\n\x05theta\x18\n \x01(\x02\x12!\n\x19transition_layers_bn_relu\x18\x0b \x01(\x08\x12\x14\n\x0cweight_deacy\x18\x0c \x01(\x02\x12\x18\n\x10head_kernel_size\x18\r \x01(\x05\x12\x18\n\x10head_stride_size\x18\x0e \x01(\x05\x12\x1d\n\x15head_pool_kernel_size\x18\x0f \x01(\x05\x12\x1d\n\x15head_pool_stride_size\x18\x10 \x01(\x05\x12\x18\n\x10output_num_class\x18\x11 \x01(\x05\x12%\n\x1dhead_block_weight_initializer\x18\x12 \x01(\t\x12\'\n\x1f\x64\x65nse_block_weights_initializer\x18\x13 \x01(\t\x12&\n\x1epool_block_weights_initializer\x18\x14 \x01(\t\x12\x13\n\x0bintern_rate\x18\x15 \x01(\x05')
)




_DENSENET = _descriptor.Descriptor(
  name='DenseNet',
  full_name='object_detection.protos.DenseNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k_size', full_name='object_detection.protos.DenseNet.k_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='L', full_name='object_detection.protos.DenseNet.L', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bias_add', full_name='object_detection.protos.DenseNet.bias_add', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dense_blocks', full_name='object_detection.protos.DenseNet.dense_blocks', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block_size', full_name='object_detection.protos.DenseNet.block_size', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='densenet_b', full_name='object_detection.protos.DenseNet.densenet_b', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout', full_name='object_detection.protos.DenseNet.dropout', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout_rate', full_name='object_detection.protos.DenseNet.dropout_rate', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='densenet_c', full_name='object_detection.protos.DenseNet.densenet_c', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta', full_name='object_detection.protos.DenseNet.theta', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transition_layers_bn_relu', full_name='object_detection.protos.DenseNet.transition_layers_bn_relu', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight_deacy', full_name='object_detection.protos.DenseNet.weight_deacy', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head_kernel_size', full_name='object_detection.protos.DenseNet.head_kernel_size', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head_stride_size', full_name='object_detection.protos.DenseNet.head_stride_size', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head_pool_kernel_size', full_name='object_detection.protos.DenseNet.head_pool_kernel_size', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head_pool_stride_size', full_name='object_detection.protos.DenseNet.head_pool_stride_size', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_num_class', full_name='object_detection.protos.DenseNet.output_num_class', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head_block_weight_initializer', full_name='object_detection.protos.DenseNet.head_block_weight_initializer', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dense_block_weights_initializer', full_name='object_detection.protos.DenseNet.dense_block_weights_initializer', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pool_block_weights_initializer', full_name='object_detection.protos.DenseNet.pool_block_weights_initializer', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intern_rate', full_name='object_detection.protos.DenseNet.intern_rate', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=573,
)

DESCRIPTOR.message_types_by_name['DenseNet'] = _DENSENET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DenseNet = _reflection.GeneratedProtocolMessageType('DenseNet', (_message.Message,), dict(
  DESCRIPTOR = _DENSENET,
  __module__ = 'densenet_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.DenseNet)
  ))
_sym_db.RegisterMessage(DenseNet)


# @@protoc_insertion_point(module_scope)
