# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='train_config.proto',
  package='object_detection.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x12train_config.proto\x12\x17object_detection.protos\"\xee\x01\n\x10train_parameters\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x19\n\x11input_config_path\x18\x02 \x01(\t\x12\x1c\n\x14\x64\x65nsenet_config_path\x18\x03 \x01(\t\x12\x15\n\rlearning_rate\x18\x04 \x01(\x02\x12\x19\n\x11weight_deacy_rate\x18\x05 \x01(\x02\x12\x14\n\x0csummary_step\x18\x06 \x01(\x05\x12\x16\n\x0etest_save_step\x18\x07 \x01(\x05\x12\x19\n\x11summary_save_path\x18\x08 \x01(\t\x12\x17\n\x0fmodel_save_path\x18\t \x01(\t')
)




_TRAIN_PARAMETERS = _descriptor.Descriptor(
  name='train_parameters',
  full_name='object_detection.protos.train_parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch', full_name='object_detection.protos.train_parameters.epoch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_config_path', full_name='object_detection.protos.train_parameters.input_config_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='densenet_config_path', full_name='object_detection.protos.train_parameters.densenet_config_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='object_detection.protos.train_parameters.learning_rate', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight_deacy_rate', full_name='object_detection.protos.train_parameters.weight_deacy_rate', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summary_step', full_name='object_detection.protos.train_parameters.summary_step', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_save_step', full_name='object_detection.protos.train_parameters.test_save_step', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summary_save_path', full_name='object_detection.protos.train_parameters.summary_save_path', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_save_path', full_name='object_detection.protos.train_parameters.model_save_path', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=286,
)

DESCRIPTOR.message_types_by_name['train_parameters'] = _TRAIN_PARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

train_parameters = _reflection.GeneratedProtocolMessageType('train_parameters', (_message.Message,), dict(
  DESCRIPTOR = _TRAIN_PARAMETERS,
  __module__ = 'train_config_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.train_parameters)
  ))
_sym_db.RegisterMessage(train_parameters)


# @@protoc_insertion_point(module_scope)
